version: '3.5'
services:
  web:
    ports:
        - "8000:80"
  db:
    ports:
        - "3306:3306"
    volumes:
        - /var/www/html/db/shelter:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: shelter-db
        MYSQL_USER: p1nk
        MYSQL_PASSWORD: p@ssw0rd
