version: '3.5'
services:
  web:
    ports:
        - "8000:80"
  db:
    ports:
        - "3307:3306"
    volumes:
        - /var/www/db/petAdoption:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: toor
        MYSQL_DATABASE: pet-db
        MYSQL_USER: p1nk
        MYSQL_PASSWORD: root
