version: '3.5'
services:
    web:
        container_name: pet-adoption-api
        build:
            context: .
            target: web
        working_dir: /var/www/html/app
        command: php artisan serve --host=0.0.0.0 --port=80
        volumes:
            - .:/var/www/html/app
        entrypoint:  [
            "/bin/sh",
            "/var/www/html/app/entrypoint.sh"
        ]
        tty: true
        networks:
            main:
                aliases:
                    - web
    db:
        container_name: pet-adoption-db
        image: mariadb:10.4
        networks:
            main:
                aliases:
                    - db
networks:
    main:
